'use client';

import { Target, TrendingUp } from 'lucide-react';
import { Label } from '../ui/label';

export default function AboutSection() {
  const principles = [
    {
      icon: (
        <div
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            justifyContent: 'center',
            width: '32px',
            height: '32px',
            borderRadius: '8px',
            background:
              'linear-gradient(135deg, rgba(124,92,252,0.15), rgba(124,92,252,0.05))',
            border: '1px solid rgba(124,92,252,0.3)',
            boxShadow: '0 2px 8px rgba(124,92,252,0.1)',
          }}
        >
          <div style={{ color: '#fff', fontSize: '16px' }}>
            <Target size={16} style={{ color: '#7c5cfc' }} />
          </div>
        </div>
      ),
      title: 'Confirmation over quantity',
      description:
        "We don't celebrate signal frequency. We measure signal quality. The CONFIRM signal tier exists specifically to surface only the highest-conviction setups.",
    },
    {
      icon: (
        <div
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            justifyContent: 'center',
            width: '32px',
            height: '32px',
            borderRadius: '8px',
            background:
              'linear-gradient(135deg, rgba(124,92,252,0.15), rgba(124,92,252,0.05))',
            border: '1px solid rgba(124,92,252,0.3)',
            boxShadow: '0 2px 8px rgba(124,92,252,0.1)',
          }}
        >
          <div style={{ color: '#fff', fontSize: '16px' }}>🧠</div>
        </div>
      ),
      title: 'You make the decisions',
      description:
        'WhipAlgo supports your analysis. It does not replace your judgment, tell you where to place stops, or promise specific outcomes.',
    },
    {
      icon: (
        <div
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            justifyContent: 'center',
            width: '32px',
            height: '32px',
            borderRadius: '8px',
            background:
              'linear-gradient(135deg, rgba(255,77,109,0.15), rgba(255,77,109,0.05))',
            border: '1px solid rgba(255,77,109,0.3)',
            boxShadow: '0 2px 8px rgba(255,77,109,0.1)',
          }}
        >
          <div style={{ color: '#fff', fontSize: '16px' }}>
            <TrendingUp size={16} style={{ color: '#7c5cfc' }} />
          </div>
        </div>
      ),
      title: 'Systematic, not emotional',
      description:
        'Every signal is generated by rules-based logic — volatility, trend alignment, and breakout detection — not opinion or discretion.',
    },
    {
      icon: (
        <div
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            justifyContent: 'center',
            width: '32px',
            height: '32px',
            borderRadius: '8px',
            background:
              'linear-gradient(135deg, rgba(255,215,64,0.15), rgba(255,215,64,0.05))',
            border: '1px solid rgba(255,215,64,0.3)',
            boxShadow: '0 2px 8px rgba(255,215,64,0.1)',
          }}
        >
          <div style={{ color: '#fff', fontSize: '16px' }}>🔒</div>
        </div>
      ),
      title: 'No hype, no false claims',
      description:
        "We don't publish win rates we can't verify. We don't claim the system \"never loses.\" We build tools that inform better decisions.",
    },
  ];

  return (
    <section
      id="about"
      className="landing-section"
      style={{ padding: '100px 48px', maxWidth: '1200px', margin: '0 auto' }}
    >
      <div
        className="about-grid"
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(2, 1fr)',
          gap: '32px',
          alignItems: 'start',
          marginTop: '32px',
        }}
      >
        <div>
          <Label variant="section-header" size="lg">
            ABOUT WHIPALGO
          </Label>
          <h2
            style={{
              fontFamily: 'Inter, sans-serif',
              fontWeight: 700,
              fontSize: 'clamp(26px, 3.5vw, 42px)',
              lineHeight: 1.15,
              letterSpacing: '-1px',
              color: '#fff',
              marginBottom: '16px',
            }}
          >
            Built by traders.
            <br />
            For traders.
          </h2>
          <p
            style={{
              fontSize: 'clamp(16px, 2vw, 18px)',
              color: '#e2e8f0',
              lineHeight: 1.75,
              marginTop: '16px',
            }}
          >
            WhipAlgo was developed out of frustration with retail trading tools
            that generate noise, make false promises, and leave traders more
            confused than when they started.
          </p>
        </div>

        <div>
          <ul
            style={{
              listStyle: 'none',
              marginTop: '32px',
              padding: 0,
              margin: 0,
            }}
          >
            {principles.map((principle, index) => (
              <li
                key={index}
                style={{
                  display: 'flex',
                  gap: '16px',
                  padding: '16px 0 16px 24px', // added left padding
                  borderBottom:
                    index === principles.length - 1
                      ? 'none'
                      : '1px solid rgba(255,255,255,0.06)',
                  transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.background = 'rgba(124,92,252,0.05)';
                  e.currentTarget.style.transform = 'translateX(4px)';
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.background = 'transparent';
                  e.currentTarget.style.transform = 'translateX(0)';
                }}
              >
                <div
                  style={{ fontSize: '20px', color: '#7c5cfc', flexShrink: 0 }}
                >
                  {principle.icon}
                </div>
                <div>
                  <div
                    style={{
                      fontWeight: 600,
                      color: '#e8e8f0',
                      fontSize: '14px',
                      marginBottom: '4px',
                    }}
                  >
                    {principle.title}
                  </div>
                  <div
                    style={{
                      color: '#e2e8f0',
                      fontSize: '13px',
                      lineHeight: 1.6,
                    }}
                  >
                    {principle.description}
                  </div>
                </div>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </section>
  );
}
