export default function AboutSection() {
  const principles = [
    {
      icon: '🎯',
      title: 'Confirmation over quantity',
      description:
        "We don't celebrate signal frequency. We measure signal quality. The CONFIRM signal tier exists specifically to surface only the highest-conviction setups.",
    },
    {
      icon: '🧠',
      title: 'You make the decisions',
      description:
        'WhipAlgo supports your analysis. It does not replace your judgment, tell you where to place stops, or promise specific outcomes.',
    },
    {
      icon: '📐',
      title: 'Systematic, not emotional',
      description:
        'Every signal is generated by rules-based logic — volatility, trend alignment, and breakout detection — not opinion or discretion.',
    },
    {
      icon: '🔒',
      title: 'No hype, no false claims',
      description:
        "We don't publish win rates we can't verify. We don't claim the system \"never loses.\" We build tools that inform better decisions.",
    },
  ];

  return (
    <section
      id="about"
      style={{ padding: '100px 48px', maxWidth: '1200px', margin: '0 auto' }}
    >
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: '1fr 1fr',
          gap: '80px',
          alignItems: 'center',
        }}
      >
        <div>
          <div
            style={{
              fontFamily: 'Space Mono, monospace',
              fontSize: '11px',
              color: '#7c5cfc',
              letterSpacing: '3px',
              textTransform: 'uppercase',
              marginBottom: '16px',
            }}
          >
            ABOUT WHIPALGO
          </div>
          <h2
            style={{
              fontFamily: 'Space Mono, monospace',
              fontWeight: 700,
              fontSize: 'clamp(26px, 3.5vw, 42px)',
              lineHeight: 1.15,
              letterSpacing: '-1px',
              color: '#fff',
              marginBottom: '16px',
            }}
          >
            Built by traders.
            <br />
            For traders.
          </h2>
          <p
            style={{
              fontSize: '16px',
              color: '#6b6b85',
              lineHeight: 1.75,
              marginTop: '16px',
            }}
          >
            WhipAlgo was developed out of frustration with retail trading tools
            that generate noise, make false promises, and leave traders more
            confused than when they started.
          </p>
        </div>

        <div>
          <ul
            style={{
              listStyle: 'none',
              marginTop: '32px',
              padding: 0,
              margin: 0,
            }}
          >
            {principles.map((principle, index) => (
              <li
                key={index}
                style={{
                  display: 'flex',
                  gap: '16px',
                  padding: '16px 0',
                  borderBottom:
                    index === principles.length - 1
                      ? 'none'
                      : '1px solid rgba(255,255,255,0.06)',
                }}
              >
                <div style={{ fontSize: '20px', flexShrink: 0 }}>
                  {principle.icon}
                </div>
                <div>
                  <div
                    style={{
                      fontWeight: 600,
                      color: '#e8e8f0',
                      fontSize: '14px',
                      marginBottom: '4px',
                    }}
                  >
                    {principle.title}
                  </div>
                  <div
                    style={{
                      color: '#6b6b85',
                      fontSize: '13px',
                      lineHeight: 1.6,
                    }}
                  >
                    {principle.description}
                  </div>
                </div>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </section>
  );
}
